{{- if .Values.JenkinsXBDD }}
apiVersion: v1
data:
  bdd-credentials.json: {{ .Values.JenkinsXBDD | quote }}
kind: Secret
metadata:
  annotations:
    # Workaround until Kubernetes Credentials Provider can deal with a secret without annotations.
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: secretText
  name: bdd-secret
type: Opaque
{{- end }}