apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  creationTimestamp: null
  name: ci-scheduler
spec:
  approve:
    issueRequired: false
    lgtmActsAsApprove: true
    requireSelfApproval: true
  merger:
    blockerLabel: ""
    maxGoroutines: 0
    mergeMethod: merge
    policy:
      fromBranchProtection: true
      optionalContexts: {}
      requiredContexts: {}
      requiredIfPresentContexts: {}
      skipUnknownContexts: false
    prStatusBaseUrl: ""
    squashLabel: ""
    targetUrl: http://deck{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
  plugins:
    entries:
    - trigger
    - override
  policy:
    protectTested: true
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: true
      branches: {}
      cluster: ""
      context: ci
      labels: {}
      maxConcurrency: 0
      mergeMethod: ""
      name: ci
      optional: false
      policy:
        Replace: false
        requiredStatusChecks:
          contexts:
            entries:
            - ci
      report: true
      rerunCommand: /test this
      runIfChanged: ""
      skipBranches: {}
      trigger: (?m)^/test( all| this),?(\s+|$)
  postsubmits:
    replace: true
  trigger:
    ignoreOkToTest: false
    joinOrgUrl: ""
    onlyOrgMembers: false
    trustedOrg: {{ .Values.gitops.owner }}
  welcome:
  - message_template: Welcome
  attachments:
  - name: jobURLPrefix
    urls:
    - 'https://dashboard-jx.jenkins-x.live/teams'
  - name: reportTemplate
    urls:
    - '{{`{{if eq .Spec.Type "presubmit"}}[View all Builds for this Pull Request](https://dashboard-jx.jenkins-x.live/teams/{{.Spec.Namespace}}/projects/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}) {{else if eq .Spec.Type "batch"}} Run "jx get build log --owner {{.Spec.Refs.Org}} --repo {{.Spec.Refs.Repo}} --branch batch" whilst connected to the cluster. UI support coming soon. {{end}}`}}'
  - name: jobURLTemplate
    urls:
    - '{{`{{if eq .Spec.Type "presubmit"}}https://dashboard-jx.jenkins-x.live/teams/{{.Spec.Namespace}}/projects/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/PR-{{(index .Spec.Refs.Pulls 0).Number}}/{{.Status.BuildID}}{{else if eq .Spec.Type "postsubmit"}}https://dashboard-jx.jenkins-x.live/teams/{{.Spec.Namespace}}/projects/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/{{.Spec.Refs.BaseRef}}/{{.Status.BuildID}}{{end}}`}}'
