apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  name: jx-scheduler
spec:
  lgtm:
    reviewActsAsLgtm: true
  merger:
    mergeMethod: rebase
  plugins:
    entries:
      - label
  postsubmits:
    replace: true
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      name: release
      context: ""
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: true
      context: integration
      name: integration
      policy:
        requiredStatusChecks:
          contexts:
            entries:
            - integration
            - tekton
            - bdd
            - lint
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test integration
      trigger: (?m)^/test( all| integration),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      context: bdd
      name: bdd
      queries:
        - labels:
            entries:
              - approved
              - lgtm
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
      report: true
      rerunCommand: /test bdd
      trigger: (?m)^/test( all| bdd),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      context: tekton
      name: tekton
      queries:
      - labels:
          entries:
           - approved
           - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      report: true
      rerunCommand: /test tekton
      trigger: (?m)^/test( all| tekton),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      context: lint
      name: lint
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
          - needs-security-review
      report: true
      rerunCommand: /test lint
      trigger: (?m)^/test( all| lint),?(\s+|$)
    - agent: tekton
      alwaysRun: false
      context: images
      name: images
      queries:
        - labels:
            entries:
              - approved
              - lgtm
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
              - needs-security-review
      report: true
      rerunCommand: /build images
      trigger: (?m)(?^/(build images),?(\s+|$)
