dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- condition: external-dns.enabled
  name: external-dns
  repository: https://charts.bitnami.com/bitnami
- name: jx-app-athens
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.17
- name: jx-app-sso
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.14
- name: jx-app-ui
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.792